---
development: &default
  db:
    adapter: sqlite3
    database: db/development.sqlite3
  pagination:
    default_per_page: 100
    max_per_page: 1000
  auth_header_key: AUTH_TOKEN

test: 
  <<: *default
  db:
    adapter: sqlite3
    database: db/test.sqlite3
